apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
#helmCharts:
#  - name: traefik
#    version: 38.0.1
#    repo: https://traefik.github.io/charts
#    releaseName: traefik
#    namespace: traefik
#    valuesFile: traefik/values.yaml
resources:
  - cert-manager/clusterIssuer.yaml
  - cert-manager/digital-ocean-secret.yaml
  - wildcard-cert.yaml