apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ip-address-pool
spec:
  addresses:
    - 192.168.3.30-192.168.3.120

---

apiVersion: metallb.io/v1beta1
kind: BGPAdvertisement
metadata:
  name: external
spec:
  ipAddressPools:
    - ip-address-pool

---

apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert